version: 2

jobs:
  build:
    working_directory: ~/leviahack.github.io
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run: yarn
      - run:
          name: EsLint Tests
          command: yarn run lint --quiet --output-file eslint-report -f node_modules/eslint-formatter-markdown/markdown.js
      - store_test_results:
          path: ~/leviahack.github.io/eslint-report
      - run: yarn test --coverage
      - store_artifacts:
          path: ~/leviahack.github.io/coverage/

workflows:
  version: 2
  commit:
    jobs:
      - build
